# install.packages(c("tidyverse", "dm", "DiagrammeR", "RSQLite", "RMariaDB", "duckdb", "duckplyr", "progress", "pixarfilms", "nycflights13", "parquetize"), type = "binary")
# pak::pak(c("tidyverse", "dm", "DiagrammeR", "RSQLite", "RMariaDB", "duckdb", "duckplyr", "progress", "pixarfilms", "nycflights13", "parquetize"))

library(tidyverse)
library(dm)
library(DiagrammeR)
library(RSQLite)
library(RMariaDB)
library(duckdb)
library(duckplyr)
library(progress)
library(pixarfilms)
library(nycflights13)
library(parquetize)
